#pragma once

void emptyFunction0();
void emptyFunction1();
void emptyFunction2();
void emptyFunction4();
void emptyFunction3();
void emptyFunction5();
void emptyFunction6();
void emptyFunction7();
void emptyFunction8();
void emptyFunction9();
void emptyFunction10();
void emptyFunction11();
void emptyFunction12();
void emptyFunction13();
void emptyFunction14();
void emptyFunction15();
void emptyFunction16();
void emptyFunction18();
void emptyFunction19();
void emptyFunction20();
void emptyFunction21();
void emptyFunction22();
void emptyFunction23();
void emptyFunction24();
void emptyFunction25();
void emptyFunction26();
void emptyFunction27();
void emptyFunction28();
void emptyFunction29();
void emptyFunction30();
void emptyFunction31();
void emptyFunction32();
void emptyFunction33();
void emptyFunction34();


int return0_2();
int return0_3();
int return0_4();
int return0_5();
int return0_6();
int return0_7();
int return0_10();
int return0_11();
int return0_12();
int return0_13();