#pragma once

#include "defs.h"

extern int languageId; // weak
extern int g_SomeLanguageVariable; // weak

void loadLanguageDatas();
int __cdecl loadLanguageString(int a1);
int initLanguage();

namespace language
{
	enum languageType
	{
		English,
		French,
		German,
		Unknown1,
		Spanish,
		Japan,
		Unknown,
	};

	//Enum for loadLanguageString(int) function.
	//Those numbers must be same as they storing in "english.lng"
	enum languageStrings
	{
		Mono = 1,
		Stereo,
		Port,
		Player1,
		Player2,
		Player3,
		Player4,
		Configuration,
		DINO,
		SPY,
		DINO_2,
		SUPER_SPY,
		SUPER_SPY_2,
		NOT_NULL,
		Speakers,
		SFX_volume,
		Music_volume,
		Hz60,
		Widescreen,
		Screen_offset,
		Centre_screen,
		GAME_1,
		GAME_2,
		GAME_3,
		On,
		Off,
		Back,
		Cancel,
		J_select,
		Select_game_file,//30
		Sound_configuration,
		Visual_options,
		Sound_options,
		Controller_configuration,
		Select_character,
		Select_level,
		Player,
		START_NEW_GAME,
		START_ROLLING_DEMO,
		LOAD_GAME,
		FLUFFMATCH,
		CONTROLLER_OPTIONS,
		SOUND_OPTIONS,
		VISUAL_OPTIONS,
		Roofus,
		Juliette,
		Bungalow,
		Tweek,
		Rico,
		Chang,
		Forward,
		J_back,
		Left,
		Right,
		Look_around,
		Select_weapon,
		Jump,
		Shoot,
		Look_up,
		Look_down,//60
		_Shoot,
		J_jump,
		Move_rotate,
		Strafe,
		Left2,
		Right2,
		J_look_up,
		Strafe_left,
		Strafe_right,
		TV_SETTINGS,
		Hz50,
		Hz60_2,
		TEST,
		THIS_SETTINGS_WILL_WORK,
		THIS_SETTINGS_WILL_MAKE,
		THIS_WILL_TEST_IF_YOUR,
		TESTING,
		WAS_THE_IMAGE_DISPLAYED,
		Yes,
		No,
		Okay,
		Number_of_players,
		_2_players,
		_3_players,
		_4_players,
		Fluff_limit,
		Time_limit,
		Game_configuration,
		CHEAT_MENU,
		Big_head_mode,//90
		Scrawners,
		Invulnerability,
		Rotate_cam,
		Walter,
		Auto_aim,
		First_person,
		All_subgames,
		Rocket_cam,
		Stereopair,
		Scally,
		Fishy_world,
		Honey_i_shrink,
		Health_boost,
		Ammo_boost,
		Tough_bears,
		Robot,
		Level_select,
		Headless_bears,
		Land_of_happy_moles,
		Cheat_21,
		Cheat_22,
		Cheat_23,
		Cheat_24,
		Cheat_25,
		Cheat_26,
		Cheat_27,
		Cheat_28,
		Cheat_29,
		Cheat_30,
		Cheat_31, //120
		Cheat_32,
		Cheat_menu,
		Token,
		Tokens,
		Please_wait,
		EMPTY,
		INSERT_VM_WITH_FUR,
		NO_FILE_SAVE_FOUND,
		Internet,
		ATTENTION,
		This_will_launch_website,
		ARE_YOU_SURE,
		You_must_be_registered_dream_passport,
		You_must_be_registered_planetweb,
		Press_J,
		Game_info,
		Options,
		OPTIONS,
		Exit_game,
		DISPLAY,
		PAUSE_MENU,
		DISPLAY_OPTIONS,
		CONFIRM_QUIT,
		DEBUG_MENU,
		Restart,
		Return_to_hub,
		Test_fluffed,
		YOU_FLUFFED_IT,
		OUT_OF_TIME,
		VIBRATION_OFF, //150
		VIBRATION_ON,
		SAVING_TO_VM,
		DO_NOT_REMOVE,
		READING_FROM_VM,
		INSERT_CONTROLLER,
		INTO_PORT_A,
		INTO_PORT_B,
		Use_adjust_screen_center,
		UNAVALAIBLE,
		Unavalaible,
		Cheat_on,
		Cheat_off,
		Use_only_vm_secret_info,
		No_vm_found_in_port_A1,
		Proceed_without_using,
		VM_and_abandon_saving,
		No_save_file_present,
		Create_save_file,
		This_will_overwrite_game,
		Do_you_want_proceed,
		Not_enought_empty_blocks,
		_d_blocks_required_for_saving,
		You_have_d_free_blocks,
		VM_ERROR,
		Couldnt_save_correctly,
		Not_loaded_correctly,
		Your_VM_file_damaged,
		Incorrect_save_version_number,
		Press_J_to_continue,
		Quit, //180
		Abandon_saving,
		NONE,
		BULLETS,
		SHELLS,
		GRENADES,
		ROCKETS,
		ENERGY,
		SMART,
		THERMAL,
		You_fluffed_it = 191, //191
		THRUST,
		SPEED,
		ENERGY,
		PLANES_LEFT,
		DANGER,
		DESCENT_TOO_QUICK,
		Press_J_to_restart,
		PLEASE_INSERT_VM_WITH_SAVE,
		NO_SAVED_GAME_FOUND,
		A_VM_is_not_inserted_into_port_1,
		Insert_VM_in_port_1,
		There_is_not_VM_into_port_1,
		There_not_free_blocks_in_VM,
		Please_wait_2,
		NO_VM_INSERTED,
		NOT_ENOUGHT_FREE_BLOCKS,
		CONTROLLER_HAS_BEEN_REMOVED,
		INVALID_CONTROLLER_IN_PORT,
		GAME_PAUSED_2, //210
		GAME_PAUSED_BY_PLAYER,
		CONFIRM_ABORT,
		You_have_chosen_to_play_without_saves,
		Your_VM_has_been_removed,
		VM_in_port_A_doesnt_contain_no_saves,
		VM_in_port_A_replace_save_game,
		SAVING_DONT_TURN_OFF,
		SAVING_DO_NOT_REMOVE_VM,
		First_person_perspective_settings,
		SAVE_ERROR,
		MULTIPLAYER_OPTIONS,
		DEMO_COMPLETED,
		_s_complete,
		Time_attack_completed,
		Time_remaining,
		TIME_TAKEN,
		KILLS,
		GOLDEN_TOKENS,
		BABIES,
		PRESS_J_TO_CONTINUE,
		PRESS_J_TO_CONTINUE_2,
		Enter_initials,
		ENTERING,
		ITS_DRAW,
		PLAYER_WINS,
		PLAYER_d,
		_d_FLUFFS,
		INSERT_VALID_CONTROLLER,
		No_controller,
		Invalid_controller, //240
		Restart_hub,
		DRAW,
		PRESS_ENTER_BUTTON,
		Save_coplete,
		INSERT_VALID_CONTROLLER_INTO_PORT,
		PLAYER,
		ROLLING_DEMO_PRESS_ENTER,
		DEMO_PLAY,
		Level_select_2,
		Check_point,
		End_of_demo,
		Exit_to,
		you_need,
		babies,
		Babies_to_enter,
		Tokens_to_enter,
		Cheat_discovered,
		Fluffs_,
		FLUFFS,
		YOU_FLUFFED,
		You_got_fluffed_press_J,
		Bang_got_fluffed_press_J,
		Thats_not_end_press_J,
		Fluffed_shame_press_J,
		Fluffed_again_press_J,
		Thats_fixed_fluff_press_J,
		Ammo,
		Health,
		TIME_ATTACK,
		You_got_all_tokens, //270
		ITEMS,
		KEY,
		KEY_2,
		ITEMS_2,
		PISTOL = 275, //275
		SHOTGUN, //276
		AUTO_SHOTGUN, //277
		SUBMATINE_GUN, //278
		HEAVY_MACHINE_GUN, //279
		BOMB_LAUNCHER, //280
		CLUSTER_BOMB, //281
		ROCKET_LAUNCHER, //282
		SEEKER_LAUNCHER, //283
		PLASMA_BUSTER, //284
		PLASMA_BEAMER, //285
		NEUTRON_GUN, //286
		FREEZE_GUN, //287
		FLAME_GUN, //288
		CLOSE_RANGE_ATTACK,
		RESCUED,
		GOLD,
		TOKENS,
		GOLD_2,
		TOKENS_2,
		Gold_2,
		Tokens_2,
		TIME,
		ATTACK,
		Gold_3,
		Silver, //300
		Bronze,
		TOTAL_TIME_IN_GAME,
		TOTAL_TIME,
		Total,
		Time,
		Total_2,
		Time_2,
		L_trigger,
		R_trigger,
		Game_will_end_after,
		Or,
		Minutes,
		Fluffs_2,
		One_hour,
		Game_will_play_indefinitely,
		Unlimited,
		Bear_disguise = 335, //335
		Meerkat_multiple,
		Beetle_shield,
		RETURN_TO_HUB,
		LOADING,
		Health_2,
		ENTER_NAME,
		SELECT_CHARACTER,
		Info_screen,
		Start_new_game,
		Join_game,
		CONTINUE,
		Enter_IP,
		Search,
		Allow_join,
		First_person_2, //250
		Start_game,
		Cancel_2,
		Level,
		Chat,
		MAX_PLAYERS,
		Headphones,
		Two_speakers,
		Surround_sound,
		Four_speakers,
		Up,
		Down,
		FORWARD,
		BACKWARD,
		STRAFE_LEFT,
		STRAFE_RIGHT,
		E_CNT_START,
		SHOOT,
		JUMP,
		NEXT_WEAPON,
		E_CNT_FIRE_4,
		CYCLE_WEAPON_UP,
		CYCLE_WEAPON_DOWN,
		E_CNT_ADJ3,
		E_CNT_ADJ4,
		E_CNT_ROTX,
		E_CNT_ROTY,
		SCORES,
		CHAT,
		NO_CONTROLS,
		Restore_defaults, //380
		Mouse_sensitivity,
		Invert_mouse,
		Crosshair,
		Bit32_rendering_off,
		Bit32_rendering_on,
		Resolution,
		Bit32_rendering,
		Gamma,
		Filtering,
		Bump_mapping,
		Press_fire_to_continue,
		Waiting_for_host_to_continue,
		Enter_IP_or_blank,
		INTERPROGATTING_NETWORK,
		NO_GAMES_FOUND,
		Select_game_to_join,
		Chat_room,
		Search_menu,
		Enter_your_name,
		Start_network_game, //400
		Enter_game_name,
		Continue,
		Enter_name,
		Max_players,
		Disable_lighting,
		Progress_saved,
		Multiplayer,
		Has_joined_game,
		Left_the_game,
		Connection_lost,
		Host_connection_lost,
		You_got_fluffed,
		Got_fluffed,
		Got_fluffed_your_self,
		Self_fluffed,
		Fluffed_you,
		You_fluffed,
		Fluffed,
		Chat_,
		Auto_aim_2,
		Waiting_for_players,
		No_sound_providers_found,
		Dynamic_lighting,
		Enter_save_slot_name //424
	};
}